### PR TITLE
Simplify structure

### PR DESCRIPTION
**Pull request by oliverjam**
The project was a bit messy and complex, so I've wanted to simplify it for a while. Apologies for there being so many changes, but most of them just involve moving files or rewriting from JS to Nunjucks.

1. Rewrite almost all `.js` templates as `.njk`
   Nunjucks can be used within Markdown, which makes writing basic pages easier. They can be almost entirely Markdown with a couple of extra Nunjucks component.
1. Move everything in `pages/` up a level (and get rid of that directory).
   It's simpler to have all the main pages at the top-level rather than having everything so nested.

I haven't touched the Events page stuff yet since it's not live. I'm gonna be looking at getting that working soon so will update then.

### CODE REVIEW

**Review by sofer — APPROVED** [review]
I had forgotten nunjucks even existed. We may have used it on FAC1--although I might be mistaking it for jinja2.

**Review by Albadylic — APPROVED** [review]
Looks good to me. I had a look through the files and didn't spot anything amiss.

**Comment by oliverjam** [comment]
@sofer 😆 yeah I think they're pretty much the same. The site is built with [Eleventy](https://11ty.dev), which defaults to Nunjucks for all the docs examples. It's kind of nice to work within a dedicated templating solution too when you're pretty much only creating static markup.

**Comment by oliverjam** [comment]
I've double-checked the deploy-preview site and all the pages look fine, so I'll merge it

**Pull request merged**
