### PR TITLE
Update team bio's

### PR DESCRIPTION
**Pull request by sofer**
Partly addresses #68

### CODE REVIEW

**Comment by oliverjam** [comment]
@sofer can this wait until my markdown refactor gets merged? If we keep changing content it's really hard to keep the branch updated (since I have to manually move changes from JSON to markdown)

**Comment by sofer** [comment]
@oliverjam how's the markdown refactor going?

**Comment by oliverjam** [comment]
Oh sorry that got merged [in August](#57). Totally forgot about this one. I'll try to resolve the conflicts

**Comment by oliverjam** [comment]
Apologies but it was easier to start again, closing in favour of #77

**Pull request closed without merging**
